/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Justice;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AttorneyOrganization;
import Business.Organization.JusticeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnquiryReportRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deivakumaran
 */
public class JusticeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JusticeWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private JusticeOrganization justiceOrganization;
    private Enterprise enterprise;
    private Ecosystem system;

    public JusticeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, JusticeOrganization justiceOrganization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.justiceOrganization = justiceOrganization;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) firTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : justiceOrganization.getWorkQueue().getWorkRequestList()) {
            if (request.getName().equalsIgnoreCase(WorkRequest.Type.Enquiry.getValue())) {
                Object[] row = new Object[6];
                row[0] = request;
                int id = ((EnquiryReportRequest) request).getEnquiryID();
                row[1] = id;
                String result = ((EnquiryReportRequest) request).getCriminalFirstName();
                row[2] = result;
                String status = ((EnquiryReportRequest) request).getStatus();
                row[3] = status;
                int number = ((EnquiryReportRequest) request).getCaseID();
                row[4] = number;
                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        firTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 232, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firTable.setBackground(new java.awt.Color(196, 232, 255));
        firTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CrimeType", "Enquiry ID", "Criminal Name", "Status", "CaseID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        firTable.setSelectionForeground(new java.awt.Color(224, 244, 255));
        jScrollPane3.setViewportView(firTable);
        if (firTable.getColumnModel().getColumnCount() > 0) {
            firTable.getColumnModel().getColumn(0).setResizable(false);
            firTable.getColumnModel().getColumn(1).setResizable(false);
            firTable.getColumnModel().getColumn(2).setResizable(false);
            firTable.getColumnModel().getColumn(3).setResizable(false);
            firTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 90));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("Manage Justice Case");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        processButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        processButton.setText("Process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        add(processButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Justice/the-weight-of-the-1783190_960_720.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        int row = firTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        EnquiryReportRequest enquiryReportRequest = (EnquiryReportRequest) firTable.getValueAt(row, 0);
        if (enquiryReportRequest.getStatus().equalsIgnoreCase("Judge Review Pending")) {
            ProcessCaseJPanel processCaseJPanel = new ProcessCaseJPanel(userProcessContainer, enquiryReportRequest);
            userProcessContainer.add("ProcessCaseJPanel", processCaseJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Decision Made!!", "Warning", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_processButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable firTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton processButton;
    // End of variables declaration//GEN-END:variables
}
