/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CommissionerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CommissionerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author deivakumaran
 */
public class CommissionerMainWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CommissionerOrganization commissionerOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ecosystem system;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CommissionerMainWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CommissionerOrganization organization, Enterprise enterprise, Ecosystem system) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.commissionerOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        populateRequestTable();

    }

    public void populateRequestTable() {
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageFIRButton = new javax.swing.JButton();
        manageCriminalsJPanel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        manageAlarmReport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 232, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("Commisioner Work Area");

        manageFIRButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        manageFIRButton.setText("Manage FIR");
        manageFIRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFIRButtonActionPerformed(evt);
            }
        });

        manageCriminalsJPanel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        manageCriminalsJPanel.setText("Manage Criminals");
        manageCriminalsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCriminalsJPanelActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Manage Case");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        manageAlarmReport.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        manageAlarmReport.setText("Manage Public Report");
        manageAlarmReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAlarmReportActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CommissionerRole/commissioner.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageCriminalsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageFIRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageAlarmReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(1207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(manageFIRButton)
                        .addGap(17, 17, 17)
                        .addComponent(manageAlarmReport)
                        .addGap(18, 18, 18)
                        .addComponent(manageCriminalsJPanel)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3))
                    .addComponent(jLabel2))
                .addContainerGap(588, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageFIRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFIRButtonActionPerformed
        // TODO add your handling code here:
        ManageCommissionerFIRJPanel manageCommissionerFIRJPanel = new ManageCommissionerFIRJPanel(userProcessContainer, enterprise, userAccount, commissionerOrganization);
        userProcessContainer.add("manageCommissionerFIRJPanel", manageCommissionerFIRJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFIRButtonActionPerformed

    private void manageCriminalsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCriminalsJPanelActionPerformed

        ManageCriminalRecordJPanel1 manageCriminalRecordJPanel1 = new ManageCriminalRecordJPanel1(userProcessContainer, commissionerOrganization, enterprise);
        userProcessContainer.add("manageCriminalRecordJPanel1", manageCriminalRecordJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCriminalsJPanelActionPerformed

    private void manageAlarmReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAlarmReportActionPerformed
        // TODO add your handling code here:
        CommissionerPublicWorkAreaJPanel commissionerPublicWorkAreaJPanel = new CommissionerPublicWorkAreaJPanel(userProcessContainer, userAccount, commissionerOrganization, enterprise);
        userProcessContainer.add("commissionerPublicWorkAreaJPanel", commissionerPublicWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_manageAlarmReportActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ManageCommissionerCaseJPanel manageCommissionerCaseJPanel = new ManageCommissionerCaseJPanel(userProcessContainer, userAccount, commissionerOrganization, enterprise, system);
        userProcessContainer.add("ManageCommissionerCaseJPanel", manageCommissionerCaseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAlarmReport;
    private javax.swing.JButton manageCriminalsJPanel;
    private javax.swing.JButton manageFIRButton;
    // End of variables declaration//GEN-END:variables
}
