/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabRole;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author deivakumaran
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private LabOrganization labOrganization;
    private Enterprise enterprise;

    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization labOrganization, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.labOrganization = labOrganization;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageFingerPrintsButton = new javax.swing.JButton();
        manageDNAButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 232, 255));

        manageFingerPrintsButton.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        manageFingerPrintsButton.setText("Manage Finger Prints");
        manageFingerPrintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFingerPrintsButtonActionPerformed(evt);
            }
        });

        manageDNAButton.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        manageDNAButton.setText("Manage DNA");
        manageDNAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDNAButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("Lab Assistant Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/LabRole/DNA.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageDNAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageFingerPrintsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(manageFingerPrintsButton)
                .addGap(40, 40, 40)
                .addComponent(manageDNAButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 634, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageFingerPrintsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFingerPrintsButtonActionPerformed
        // TODO add your handling code here:
        ManageFingerPrintJPanel manageFingerPrintJPanel = new ManageFingerPrintJPanel(userProcessContainer, enterprise, labOrganization, account);
        userProcessContainer.add("ManageFingerPrintJPanel", manageFingerPrintJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFingerPrintsButtonActionPerformed

    private void manageDNAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDNAButtonActionPerformed
        // TODO add your handling code here:
        ManageDNAJPanel manageDNAJPanel = new ManageDNAJPanel(userProcessContainer, enterprise, labOrganization, account);
        userProcessContainer.add("ManageDNAJPanel", manageDNAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDNAButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageDNAButton;
    private javax.swing.JButton manageFingerPrintsButton;
    // End of variables declaration//GEN-END:variables
}
